[tool.poetry]
name = "blueflow-agent"
version = "0.1.0"
description = ""
authors = ["4roring <4roring@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyautogui = "^0.9.54"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
